# Generated by Django 4.0.4 on 2022-10-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_delete_addressdetails_delete_contactdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
